spring.application.name=practicaweb

spring.datasource.url=jdbc:postgresql://localhost:5432/practicadb
spring.datasource.username=alba
spring.datasource.password=ej84nnwy
spring.security.user.name=alba
spring.security.user.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false